---
development:
  dialect: postgres
  database: callofduty_development
  user: {{envOr "DATABASE_USER" "postgres"}}
  password: {{envOr "DATABASE_PASSWORD" "postgres"}}
  host: {{envOr "DATABASE_HOST" "127.0.0.1"}}
  pool: {{envOr "DATABASE_CONN_POOL" "10"}}

test:
  dialect: postgres
  database: callofduty_test
  user: {{envOr "DATABASE_USER" "postgres"}}
  password: {{envOr "DATABASE_PASSWORD" "postgres"}}
  host: {{envOr "DATABASE_HOST" "127.0.0.1"}}
  pool: {{envOr "DATABASE_CONN_POOL" "10"}}

production:
  dialect: postgres
  database: callofduty_production
  user: {{envOr "DATABASE_USER" "postgres"}}
  password: {{envOr "DATABASE_PASSWORD" "postgres"}}
  host: {{envOr "DATABASE_HOST" "127.0.0.1"}}
  pool: {{envOr "DATABASE_CONN_POOL" "20"}}
