apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-of-duty
  labels:
    app: call-of-duty
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: call-of-duty
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: call-of-duty
        tier: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GO_ENV
              value: {{ .Values.environment }}
            - name: DATABASE_HOST
              value: call-of-duty-db
            - name: DATABASE_PASSWORD
              value: {{ .Values.dbPassword }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
