apiVersion: v1
kind: Service
metadata:
  name: call-of-duty
  labels:
    app: call-of-duty
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: call-of-duty
    tier: frontend
